# Generated by Django 3.2.20 on 2023-11-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_errorlog_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
